### ISSUE TITLE
excuse...could you upload your datasets or re-submit the download link for the datasets? ? because the link to the dataset given in the code has failed.

### ISSUE THREAD

**Issue by babywallance** [blmhemu/coarse-fine-classification#1]

**Comment by blmhemu** [comment]
Hey ! I'm sorry for the lost dataset. It was a course project and the dataset was probably taken out later. But the structure of the dataset is :
* Root Dir
   * Coarse classes (Cars, Planes, Birds, Cats, Dogs)
       * Fine classes (Cars -> SUV, Sedan, Hatchback etc.)
